name: build

on: [push, pull_request]

jobs:

  build:

    runs-on: windows-latest

    strategy:

      fail-fast: false
      matrix:
        build_type: [Release]
        enable_ui: [on]

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - uses: seanmiddleditch/gha-setup-ninja@master

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Generating Makefiles
      shell: bash
      run: |
        curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip
        7z x skia.zip
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_UI=${{ matrix.enable_ui }} \
          -DENABLE_CCACHE=off \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib

    - name: Compiling
      shell: bash
      run: |
        cd build && ninja

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: aseprite
        path: |
          build/bin/data
          build/bin/aseprite.exe
